// Reads the single-file offline webapp bundle (mobile/webapp/dist/index.html,
// produced by `npm run build` in mobile/webapp) and embeds it as a TypeScript
// string constant that the Expo app's WebView loads directly - no bundler
// config needed to import raw HTML, and no separate asset file to ship.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const distHtmlPath = path.resolve(__dirname, '../webapp/dist/index.html');
const outPath = path.resolve(__dirname, '../app/webapp.generated.ts');

if (!fs.existsSync(distHtmlPath)) {
  console.error(`Missing ${distHtmlPath}. Run "npm run build" in mobile/webapp first.`);
  process.exit(1);
}

const html = fs.readFileSync(distHtmlPath, 'utf8');

const out = `// AUTO-GENERATED by mobile/scripts/embed-webapp.mjs - do not edit by hand.
// Rebuild with: (cd mobile/webapp && npm run build && npm run embed)
export const WEBAPP_HTML = ${JSON.stringify(html)};
`;

fs.writeFileSync(outPath, out);
console.log(`Embedded ${(html.length / 1024).toFixed(1)} KB of HTML into ${path.relative(process.cwd(), outPath)}`);
